spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12311
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=GMT%2B8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/